import { TABLE_KEY } from './table-key.config.ts'
import { DASHBOARD_QUERY_KEYS } from './query-keys.config.ts'
import { EXCEL_REPORT_KEYS } from '../pages/Dashboard/reports/reports.data.ts'

export const BASE_URL: string =
  import.meta.env.VITE_BASE_URL || 'https://kibutsuji-cinema.vercel.app/api'

export const API_ENDPOINTS = {
  LOGIN: `${BASE_URL}/login`,
  TOKEN: `${BASE_URL}/token-check`,

  QUANTITY: `${BASE_URL}/dashboard/quantity`,
  TOP_ANIME_VIEWS: `${BASE_URL}/dashboard/top-anime-views`,
  TOP_ANIME_RATINGS: `${BASE_URL}/dashboard/top-anime-ratings`,

  ANIME_REPORT: `${BASE_URL}/reports/anime-report`,
  SUBSCRIPTIONS_REPORT: `${BASE_URL}/reports/subscriptions-report`,
  SUBSCRIPTION_AGREEMENT: `${BASE_URL}/reports/subscription-agreement`,

  [TABLE_KEY.ANIME]: `${BASE_URL}/anime`,
  [TABLE_KEY.COMMENTS]: `${BASE_URL}/comments`,
  [TABLE_KEY.EPISODES]: `${BASE_URL}/episodes`,
  [TABLE_KEY.GENRES]: `${BASE_URL}/genres`,
  [TABLE_KEY.LIKES]: `${BASE_URL}/likes`,
  [TABLE_KEY.LISTS]: `${BASE_URL}/lists`,
  [TABLE_KEY.RATINGS]: `${BASE_URL}/ratings`,
  [TABLE_KEY.SUBSCRIPTIONS]: `${BASE_URL}/subscriptions`,
  [TABLE_KEY.TRANSACTIONS]: `${BASE_URL}/transactions`,
  [TABLE_KEY.USERS]: `${BASE_URL}/users`,
} as const

export const CRUD_ENDPOINTS = {
  [TABLE_KEY.ANIME]: API_ENDPOINTS.ANIME,
  [TABLE_KEY.COMMENTS]: API_ENDPOINTS.COMMENTS,
  [TABLE_KEY.EPISODES]: API_ENDPOINTS.EPISODES,
  [TABLE_KEY.GENRES]: API_ENDPOINTS.GENRES,
  [TABLE_KEY.LIKES]: API_ENDPOINTS.LIKES,
  [TABLE_KEY.LISTS]: API_ENDPOINTS.LISTS,
  [TABLE_KEY.RATINGS]: API_ENDPOINTS.RATINGS,
  [TABLE_KEY.SUBSCRIPTIONS]: API_ENDPOINTS.SUBSCRIPTIONS,
  [TABLE_KEY.TRANSACTIONS]: API_ENDPOINTS.TRANSACTIONS,
  [TABLE_KEY.USERS]: API_ENDPOINTS.USERS,
} as const

export const DASHBOARD_API_ENDPOINTS = {
  [DASHBOARD_QUERY_KEYS.QUANTITY]: API_ENDPOINTS.QUANTITY,
  [DASHBOARD_QUERY_KEYS.TOP_ANIME_VIEWS]: API_ENDPOINTS.TOP_ANIME_VIEWS,
  [DASHBOARD_QUERY_KEYS.TOP_ANIME_RATINGS]: API_ENDPOINTS.TOP_ANIME_RATINGS,
} as const

export const EXCEL_API_ENDPOINTS = {
  [EXCEL_REPORT_KEYS.ANIME]: API_ENDPOINTS.ANIME_REPORT,
  [EXCEL_REPORT_KEYS.SUBSCRIPTIONS]: API_ENDPOINTS.SUBSCRIPTIONS_REPORT,
} as const
