export const TABLE_KEY = {
  ANIME: 'ANIME',
  COMMENTS: 'COMMENTS',
  EPISODES: 'EPISODES',
  GENRES: 'GENRES',
  LIKES: 'LIKES',
  LISTS: 'LISTS',
  RATINGS: 'RATINGS',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  TRANSACTIONS: 'TRANSACTIONS',
  USERS: 'USERS',
  AUTHORS: 'AUTHORS',
} as const

export type TCrudEndpointKeys = (typeof TABLE_KEY)[keyof typeof TABLE_KEY]
